FORMAT: 1A



# bpm

BPM API.

# BPM API Root [/rest/bpm/kb/v1]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

It is recommend to follow the “url” link values,
[Link](https://tools.ietf.org/html/rfc5988) or Location headers where
applicable to retrieve resources. Instead of constructing your own URLs,
to keep your client decoupled from implementation details.

## Retrieve the available resources [GET]

+ Response 200 (application/json; charset=utf-8)
        
        {
            "tasks_url": "/tasks"
        }


# Group Federated Systems
Information about federated systems.

## Systems [/rest/bpm/kb/v1/systems]

+ Attributes (object)
    + federationResult (array[Federation Result], required)
    + systems (array[Federated System], required)

### Systems [GET]

Use this method to retrieve metadata for one or more federated IBM BPM systems. The attributes that are returned for each system depend on the system type.


+ Request (application/json)
    + Attributes (Systems)
+ Response 200 (application/json)

+ Request Example (application/json)
+ Response 200 (application/json)

        {
        "federationResult": [
            {
                "indexRefreshInterval": 1000,
                "id": "bpm85eiplf1",
                "statusCode": 200,
                "taskCompletionUrlPrefix": "https://vnvrh687.sos.kb.cz:10402/teamworks",
                "restUrlPrefix": "https://vnvrh687.sos.kb.cz:10402/rest/bpm/wle",
                "systemType": "SYSTEM_TYPE_WLE",
                "indexName": "bpm85eiplf1",
                "systemID": "d025037a-372b-42c2-ab87-72e3cc9c4bd5",
                "version": "8.5.6.0"
            },
            {
                "indexRefreshInterval": 1000,
                "id": "wmtbpel1",
                "statusCode": 200,
                "taskCompletionUrlPrefix": "http://vnnrh662.sos.kb.cz:10401/rest/bpm/htm",
                "restUrlPrefix": "http://vnnrh662.sos.kb.cz:10401/rest/bpm/htm",
                "systemType": "SYSTEM_TYPE_WPS",
                "indexName": "wmtbpel1",
                "systemID": "_PK:9023014d.add80b66.5f8ef9f5.5c730000",
                "version": "8.5.5.0"
            }
        ],
        "systems": [
            {
                "systemID": "d025037a-372b-42c2-ab87-72e3cc9c4bd5",
                "systemType": "SYSTEM_TYPE_WLE",
                "version": "8.5.6.0",
                "groupWorkItemsEnabled": false,
                "resources": [
                    "tasks",
                    "taskTemplates",
                    "processes"
                ],
                "taskHistoryEnabled": false,
                "buildLevel": "BPM8560-20150304-164853",
                "substitutionEnabled": false,
                "workBasketsEnabled": false,
                "substitutionManagementRestrictedToAdministrators": false,
                "businessCategoriesEnabled": false,
                "taskSearchEnabled": true,
                "notificationWebMessagingEnabled": false,
                "taskListWebMessagingEnabled": false,
                "apiVersion": "1.0",
                "supports": null,
                "hostname": "brm-ibm-poc.kb.cz"
            },
            {
                "systemID": "_PK:9023014d.add80b66.5f8ef9f5.5c730000",
                "systemType": "SYSTEM_TYPE_WPS",
                "version": "8.5.5.0",
                "groupWorkItemsEnabled": false,
                "resources": [
                    "tasks",
                    "taskTemplates",
                    "escalations",
                    "workBaskets",
                    "businessCategories",
                    "processes",
                    "processTemplates",
                    "activities"
                ],
                "taskHistoryEnabled": true,
                "buildLevel": "BPM8550 [20140530-222725.0]",
                "substitutionEnabled": false,
                "workBasketsEnabled": false,
                "substitutionManagementRestrictedToAdministrators": false,
                "businessCategoriesEnabled": false,
                "groupCaseSensitivity": "CASE_CONVERSION_NONE",
                "userCaseSensitivity": "CASE_CONVERSION_NONE",
                "serverLocale": "en_US"
            }
        ]
        }
        
# Group Task List

Resources related to task lists.

## Task Queries [/rest/bpm/kb/v1/tasks/queries]

Returns all supported task queries (task lists)

+ Attributes (object)
    + federationResult (array[Federation Result], required)
    + items (array[Task Query Item], required)
    + identifier: name (string, required) Name of the field where unique identifier for Task Query is stored
    

### Queries [GET]

Currently the only supported task list is 'KB.TASKLIST' which returns tasks for the current user.

+ Request (application/json)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Task Queries)

+ Request Example (application/json)
+ Response 200 (application/json; charset=utf-8)

        {
            "federationResult": [
                {
                    "indexRefreshInterval": 1000,
                    "id": "bpm85eiplf1",
                    "statusCode": 200,
                    "taskCompletionUrlPrefix": "https://vnvrh687.sos.kb.cz:10402/teamworks",
                    "restUrlPrefix": "https://vnvrh687.sos.kb.cz:10402/rest/bpm/wle",
                    "systemType": "SYSTEM_TYPE_WLE",
                    "indexName": "bpm85eiplf1",
                    "systemID": "d025037a-372b-42c2-ab87-72e3cc9c4bd5",
                    "version": "8.5.6.0"
                },
                {
                    "indexRefreshInterval": 1000,
                    "id": "wmtbpel1",
                    "statusCode": 200,
                    "taskCompletionUrlPrefix": "http://vnnrh662.sos.kb.cz:10401/rest/bpm/htm",
                    "restUrlPrefix": "http://vnnrh662.sos.kb.cz:10401/rest/bpm/htm",
                    "systemType": "SYSTEM_TYPE_WPS",
                    "indexName": "wmtbpel1",
                    "systemID": "_PK:9023014d.add80b66.5f8ef9f5.5c730000",
                    "version": "8.5.5.0"
                }
            ],
            "items": [
                {
                    "authorizationType": "INSTANCE_BASED",
                    "kind": "FEDERATED",
                    "entityTypeName": "TASK",
                    "systemIDs": [
                        "d025037a-372b-42c2-ab87-72e3cc9c4bd5",
                        "_PK:9023014d.add80b66.5f8ef9f5.5c730000"
                    ],
                    "locales": [
                        "zh",
                        "tr",
                        "sv",
                        "ru",
                        "ro",
                        "pl",
                        "no",
                        "nb",
                        "ko",
                        "ja",
                        "default",
                        "en",
                        "ar",
                        "cs",
                        "da",
                        "de",
                        "el",
                        "es",
                        "fi",
                        "fr",
                        "iw",
                        "hu",
                        "it",
                        "zh_TW",
                        "pt_BR"
                    ],
                    "name": "IBM.DEFAULTALLTASKSLIST_75",
                    "description": "This is the default tasks list. Define custom tasks lists to show selected business data.",
                    "displayName": "All",
                    "keyAttribute": "TASK.TKIID"
                }
            ],
            "identifier": "name"
        }



## KB Task List [/rest/bpm/kb/v1/tasks/query/{queryName}{?systemID,selectedAttributes,interactionFilter,queryFilter,searchFilter,processAppName,sortAttributes,offset,size}]

Returns tasks based on specified parameters.

+ Parameters
    + queryName: KB.TASKLIST (string, required) - Unique identifier of Task Query
    + systemID: `d025037a-372b-42c2-ab87-72e3cc9c4bd5` (string, optional) - The ID of a federated IBM BPM system. Use the ID to filter the results for a specific federated system. 
    + selectedAttributes: string (string, optional) - Comma-separated list of attributes that are to be retrieved by the query.
    + interactionFilter (enum, optional) - Name of a predefined user interaction filter.
        + `WORK_ON` - Work on tasks. Returns tasks that are claimed by the current user. Tasks in suspended process instances are excluded. 
        + `ASSESS_AVAILABLE` - Assess available tasks. Returns tasks that can be claimed by the current user. Tasks in suspended process instances are excluded. 
        + `ASSESS_AND_WORK_ON` - `Assess and work on tasks. Returns tasks from the WORK_ON and the ASSESS_AVAILABLE filters.`
        + `CHECK_COMPLETED` - Completed tasks. Returns tasks which were completed by the current user. 
        + `BROWSE_ALL` - All tasks that the current user can claim, work on, or completed. Tasks in suspended process instances are included.
            This is the default value for the interactionFilter if none is specified.

    + queryFilter: string (string, optional) - 
    + searchFilter: string (string, optional) - 
    + processAppName: string (string, optional) - 
    + sortAttributes: string (string, optional) - 
    + offset: 25 (number, optional) - integer of how to offset
    + size: 100 (number, optional) - number of returned results
    
+ Attributes
    + entityTypeName (enum, required)
        + TASK (string)
    + federationResult (array[Federation Result], required) 
    + totalCount: 69 (number, required)
    + items (array[Task List Item], required)
    + query: `KB.TASKLIST` (string, required)
    + attributeInfo (array[Attribute Info], required)
    + requestedSize: 25 (number, required),
    + offset: 0 (number, required)
    + identifier: `TASK.TKIID`(string, required)
    + size: 25 (number, required)
    
    

### Queries tasks for the current user [GET]
    
+ Request (application/json)
+ Response 200 (application/json; charset=utf-8)

        {
        "entityTypeName": "TASK",
        "federationResult": [
        {
            "indexRefreshInterval": 1000,
            "id": "bpm85eiplf1",
            "statusCode": 200,
            "taskCompletionUrlPrefix": "https://vnvrh687.sos.kb.cz:10402/teamworks",
            "restUrlPrefix": "https://vnvrh687.sos.kb.cz:10402/rest/bpm/wle",
            "systemType": "SYSTEM_TYPE_WLE",
            "indexName": "bpm85eiplf1",
            "systemID": "d025037a-372b-42c2-ab87-72e3cc9c4bd5",
            "version": "8.5.6.0"
        },
        {
            "indexRefreshInterval": 1000,
            "id": "wmtbpel1",
            "statusCode": 200,
            "taskCompletionUrlPrefix": "http://vnnrh662.sos.kb.cz:10401/rest/bpm/htm",
            "restUrlPrefix": "http://vnnrh662.sos.kb.cz:10401/rest/bpm/htm",
            "systemType": "SYSTEM_TYPE_WPS",
            "indexName": "wmtbpel1",
            "systemID": "_PK:9023014d.add80b66.5f8ef9f5.5c730000",
            "version": "8.5.5.0"
        }
         ],
        "totalCount": 2,
        "items": [
        {
            "dueTime": "2014-05-05T01:06:40Z",
            "activationTime": "2015-06-26T09:54:59Z",
            "isAtRisk": true,
            "atRiskTime": "2015-06-26T09:54:59Z",
            "state": "STATE_READY",
            "name": "HT120",
            "displayName": "Zpracovat žádost",
            "originator": "deadmin",
            "priority": 30,
            "priorityName": "Normal",
            "tkiid": "671",
            "TASK.TKIID": "671",
            "status": "New_or_Received",
            "owner": "A3KOMA",
            "assignedToDisplayName": "New Team 3",
            "description": null,
            "piid": "561",
            "processInstanceName": "Assign Based on Filter Service",
            "systemID": "d025037a-372b-42c2-ab87-72e3cc9c4bd5"
            },
            {
            "dueTime": "2014-05-05T01:06:40Z",
            "activationTime": "2015-06-26T09:54:59Z",
            "isAtRisk": true,
            "atRiskTime": "2015-06-26T09:54:59Z",
            "state": "STATE_READY",
            "name": "HT120",
            "displayName": "Zpracovat žádost",
            "originator": "deadmin",
            "priority": 30,
            "priorityName": "Normal",
            "tkiid": "_TKI:3Aa01b014f.6a1e4ac6.5d8ef9f5.3a890a19",
            "TASK.TKIID": "_TKI:3Aa01b014f.6a1e4ac6.5d8ef9f5.3a890a19",
            "status": "New_or_Received",
            "owner": "A3KOMA",
            "assignedToDisplayName": "New Team 3",
            "description": null,
            "piid": "561",
            "processInstanceName": "Assign Based on Filter Service",
            "systemID": "d025037a-372b-42c2-ab87-72e3cc9c4bd5"
        }
        ],
        "query": "KB.TASKLIST",
        "attributeInfo": [
        {
            "content": "task.invokedinstanceid.key",
            "sourceAttribute": "task.invokedinstanceid.key",
            "name": "INVOKED_INSTANCE_ID",
            "sourceQueryTableIdentifier": "n/a",
            "type": "string",
            "isArray": false
        }
        ],
        "requestedSize": 25,
        "offset": 0,
        "identifier": "TASK.TKIID",
        "size": 25
        }
   
+ Request (application/json)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (KB Task List)
    
  
# Group Launchable Entities

## Launchable Entities [/rest/bpm/federated/v1/launchableEntities{?includeServiceSubtypes,excludeDashboardDuplicates,includeSystemTypes,systemID}]

Use this resource to provide a federated launch list. The list includes entities from all the federated IBM BPM systems.

+ Parameters
    + includeServiceSubtypes (enum, optional) - A comma-separated list of service subtypes that are to be included in the result set
    
        `For example, to include url and startable_service service subtypes, specify: includeServiceSubtypes=startable_service,url. If this parameter is not specified, all the service subtypes are included in the result set.`
        
        + startable_service
        + url
        + dashboard
    + excludeDashboardDuplicates: false (boolean, optional)
        If dashboard services from duplicate snapshots are found on multiple federated IBM BPM systems, all copies of the dashboard are returned by default. The user can then see the non-federated dashboard content for each federated system. If you set the value of the parameter to true, duplicate copies of the dashboard are excluded. The default value of the parameter is false. 
    + includeSystemTypes (enum, optional) - This parameter determines which system types are returned in the result set. 
        + ALL - default
        + `SYSTEM_TYPE_WLE`
        + `SYSTEM_TYPE_WPS`
    + systemID (string, optional) - If the systemID parameter is present and it matches the systemID of a federated IBM BPM system, data is returned from this system only

### Get Launchables [GET]

+ Response 200 (application/json; charset=utf-8)

        {
            "federationResult": [
                {
                    "statusCode": 200,
                    "id": "bpm85eiplf1",
                    "indexRefreshInterval": 1000,
                    "taskCompletionUrlPrefix": "https://vnvrh687.sos.kb.cz:10402/teamworks",
                    "restUrlPrefix": "https://vnvrh687.sos.kb.cz:10402/rest/bpm/wle",
                    "systemType": "SYSTEM_TYPE_WLE",
                    "indexName": "bpm85eiplf1",
                    "systemID": "d025037a-372b-42c2-ab87-72e3cc9c4bd5",
                    "version": "8.5.6.0"
                }
            ],
            "items": [
                {
                    "snapshotID": "2064.05ac3517-d400-4059-8bc3-aac9c069c2a8",
                    "itemID": "25.78c1a8c3-e207-45ab-9700-3d9e6d5cf579",
                    "systemType": "SYSTEM_TYPE_WLE",
                    "processAppName": "Hiring Sample",
                    "isMobileReady": false,
                    "launchableEntityType": "PROCESS",
                    "snapshotCreatedOn": "2015-06-30T14:04:23Z",
                    "display": "NarrativeTestingProcess",
                    "type": "process",
                    "startURL": "https://vnvrh687.sos.kb.cz:10402/rest/bpm/wle/v1/process?action=start&bpdId=25.78c1a8c3-e207-45ab-9700-3d9e6d5cf579&branchId=2063.1a52abd6-b068-4f9e-91a9-ded9793eb34e",
                    "tip": true,
                    "processAppID": "2066.9ab0d0c6-d92c-4355-9ed5-d8a05acdc4b0",
                    "branchID": "2063.1a52abd6-b068-4f9e-91a9-ded9793eb34e",
                    "isDefault": false,
                    "itemReference": "/25.78c1a8c3-e207-45ab-9700-3d9e6d5cf579",
                    "ID": "2015.294",
                    "branchName": "Main",
                    "systemID": "d025037a-372b-42c2-ab87-72e3cc9c4bd5",
                    "processAppAcronym": "HSS"
                },
                {
                    "snapshotID": "2064.b6891ab2-e94a-414e-a8eb-d51b03779ece",
                    "itemID": "1.be989f55-74be-48f4-99a4-474ff2203e12",
                    "systemType": "SYSTEM_TYPE_WLE",
                    "processAppName": "Consumer Loan",
                    "isMobileReady": false,
                    "launchableEntityType": "SERVICE",
                    "snapshotCreatedOn": "2015-08-26T12:32:34Z",
                    "display": "Report prodeje",
                    "type": "service",
                    "startURL": "https://vnvrh687.sos.kb.cz:10402/teamworks/executeServiceByName?processApp=CONLOAN&serviceName=Report+prodeje&branchId=2063.7f30ffee-528f-46eb-b93e-cbb97647523e&zResumable=true",
                    "tip": true,
                    "processAppID": "2066.ddee3d07-a4f8-4f20-b664-4143a1a2ea59",
                    "branchID": "2063.7f30ffee-528f-46eb-b93e-cbb97647523e",
                    "isDefault": false,
                    "subtype": "dashboard",
                    "itemReference": "/1.be989f55-74be-48f4-99a4-474ff2203e12",
                    "ID": "2015.125",
                    "branchName": "Main",
                    "systemID": "d025037a-372b-42c2-ab87-72e3cc9c4bd5",
                    "processAppAcronym": "CONLOAN"
                }
            ]
        }

# Group Task

## Task details [/rest/bpm/kb/v1/task/{taskID}{?systemID}]
+ Parameters
    + taskID: string (required, string) - ID of the Task, TKIID.
    + systemID: string (required, string) - ID of the system the task belongs to.

### Get Task Details [GET]

+ Request (application/json)
+ Response 200 (application/json; charset=utf-8)

         {
            "status":"200",
            "data":
            {
                "activationTime":"2014-06-23T20:39:47Z",
                "atRiskTime":"2014-06-23T20:39:47Z",
                "completionTime":"2014-06-23T20:39:47Z",
                "description":"",
                "displayName":"Step: Send escalation notice",
                "dueTime":"2014-06-23T20:39:47Z",
                "isAtRisk":true,
                "lastModificationTime":"2014-06-23T20:39:47Z",
                "name":"Send escalation notice",
                "originator":"admind",
                "owner":"admind",
                "priority":30,
                "priorityName": "Normal",
                "state":"STATE_FINISHED",
                "status":"Closed"
                "tkiid":"150",
                "piid":"54",
                "processInstanceName":"Standard Employee Requisition for Tim Horton (Standard HR Open New Position)",
                "assignedTo": "A3KOMA",
                "assignedToDisplayName": "PERFORMANCE ALENA",
                "assignedToType": "user",
                "actions":
                        [
                          "ACTION_CANCELCLAIM", 
                          "ACTION_CLAIM", 
                          "ACTION_COMPLETE",
                          "ACTION_CREATEMESSAGE", 
                          "ACTION_GETTASK", 
                          "ACTION_GETUISETTINGS", 
                          "ACTION_UPDATEDUEDATE", 
                          "ACTION_UPDATEPRIORITY", 
                          "ACTION_REASSIGNTOUSER", 
                          "ACTION_REASSIGNTOGROUP", 
                          "ACTION_VIEW_TASK"
                        ],
                "taskURL": "https://bpm-uat2.kb.cz/fe/?sequence=0.fmid=FEAK;0.faid=navigator;0.operation=hide;1.fmid=tasksLap;1.faid=showHumanTaskDetailAction;1.htTKIID=_TKI%3Aa01b014f.6a1e4ac6.5d8ef9f5.3a890a19"
                "systemID": "d025037a-372b-42c2-ab87-72e3cc9c4bd5"
                
            }
        }

# Group Task Instance

    
## Assign task [POST /rest/bpm/kb/v1/task/{taskID}{?systemID,action,toMe,back}]
At least on of toMe, back request parameters should be specified. If both are specified the values must differ.

+ Parameters
    + taskID: 459 (required, string) - ID of the Task, TKIID.
    + systemID: `d025037a-372b-42c2-ab87-72e3cc9c4bd5` (required, string) - ID of the system to retreive tasks from
    + action: assign (required, enum) - Action to be performed for the specified task instance.
        + assign (string) - Assign the specified task to the current user, to another user, to a group, or back to the original task owner, depending on the specified options. Note that exactly one of the parameters "toMe", "back", "toUser", and "toGroup" should be specified in addition to this parameter.
    + toMe: true (optional, boolean) - If specified as "true" then the task is assigned to the current user.
    + back: false (optional, boolean) - If specified as "true" then the task is assigned back to the original owner.
        
+ Request (application/json)
+ Response 200

        {
            "status":"200",
            "data":
            {
                "activationTime":"2014-06-23T20:39:47Z",
                "atRiskTime":"2014-06-23T20:39:47Z",
                "completionTime":"2014-06-23T20:39:47Z",
                "description":"",
                "displayName":"Step: Send escalation notice",
                "dueTime":"2014-06-23T20:39:47Z",
                "isAtRisk":true,
                "lastModificationTime":"2014-06-23T20:39:47Z",
                "name":"Send escalation notice",
                "originator":"admind",
                "owner":"admind",
                "priority":30,
                "priorityName": "Normal",
                "state":"STATE_FINISHED",
                "status":"Closed"
                "tkiid":"150",
                "piid":"54",
                "processInstanceName":"Standard Employee Requisition for Tim Horton (Standard HR Open New Position)",
                "assignedTo": "A3KOMA",
                "assignedToDisplayName": "PERFORMANCE ALENA",
                "assignedToType": "user",
                "actions":
                        [
                          "ACTION_CANCELCLAIM", 
                          "ACTION_CLAIM", 
                          "ACTION_COMPLETE",
                          "ACTION_CREATEMESSAGE", 
                          "ACTION_GETTASK", 
                          "ACTION_GETUISETTINGS", 
                          "ACTION_UPDATEDUEDATE", 
                          "ACTION_UPDATEPRIORITY", 
                          "ACTION_REASSIGNTOUSER", 
                          "ACTION_REASSIGNTOGROUP", 
                          "ACTION_VIEW_TASK"
                        ],
                "taskURL": "https://bpm-uat2.kb.cz/fe/?sequence=0.fmid=FEAK;0.faid=navigator;0.operation=hide;1.fmid=tasksLap;1.faid=showHumanTaskDetailAction;1.htTKIID=_TKI%3Aa01b014f.6a1e4ac6.5d8ef9f5.3a890a19"
                "systemID": "d025037a-372b-42c2-ab87-72e3cc9c4bd5"
                
            }
        }


# Group Task Actions

## Task Actions [/rest/bpm/kb/v1/task/actions{?taskID,systemID,actions}]

+ Parameters
    + taskID: string (required, string) - ID of the Task, TKIID.
    + systemID (required, string) - TODO
    + actions (optional, string) - A comma-separated list of actions the caller is interested in, used as a filter for the response.

### List of task actions [GET]
List of actions that can be performed on task instances (TaskActions complexType).    
+ Response 200 (application/json; charset=utf-8)

        {
            "status": "200",
            "data":
            {
                "identifier": "tkiid",
                "tasks":
                [
                    { 
                        "tkiid": "150",
                        "actions":
                        [
                          "ACTION_CANCELCLAIM", 
                          "ACTION_CLAIM", 
                          "ACTION_COMPLETE",
                          "ACTION_CREATEMESSAGE", 
                          "ACTION_GETTASK", 
                          "ACTION_GETUISETTINGS", 
                          "ACTION_UPDATEDUEDATE", 
                          "ACTION_UPDATEPRIORITY", 
                          "ACTION_REASSIGNTOUSER", 
                          "ACTION_REASSIGNTOGROUP", 
                          "ACTION_VIEW_TASK"
                        ]
                    }
                ]
            }
        }

## Update Task Priority [/rest/bpm/wle/v1/task/{taskID}{?systemID,action,priority,parts}]

+ Parameters
    + taskID: 904 (required, string) - A comma-separated list of IDs of human tasks for which available actions should be returned.
    + systemID: `d025037a-372b-42c2-ab87-72e3cc9c4bd5` (string, optional) - The ID of a federated IBM BPM system. Use the ID to filter the results for a specific federated system. 
    + action: update (required, enum) - Action to be performed for the specified task instance.
    + priority: High (required, enum) - Value of priority.
    + parts: actions (required, enum) - Set of data result.

### Update Priority [PUT]
Update task priority to specified value.
+ Response 200 (application/json; charset=utf-8)

        {
            "status": "200",
            "data": {
                "activationTime": "2015-09-08T13:00:12Z",
                "atRiskTime": "2015-09-08T13:26:49Z",
                "clientTypes": [
                    "IBM_WLE_Coach"
                ],
                "completionTime": null,
                "containmentContextID": "1322",
                "description": "",
                "displayName": "Step: Zpracovat žádost",
                "isAtRisk": true,
                "kind": "KIND_PARTICIPATING",
                "lastModificationTime": "2015-09-08T13:00:37Z",
                "originator": "deadmin",
                "priority": 20,
                "startTime": "2015-09-08T13:00:12Z",
                "state": "STATE_CLAIMED",
                "piid": "1322",
                "processInstanceName": "Prodej spotřebitelského úvěru:1322",
                "priorityName": "High",
                "externalActivitySnapshotID": null,
                "serviceID": "1.c872bff2-8a0f-41b0-836f-dc3ba2779eb0",
                "serviceSnapshotID": "2064.90d313be-a009-47d1-9a06-e0e6b25053c9",
                "flowObjectID": "bpdid:9b8f4cda16524d91:eb1694c:14277a1fbe1:-7f26",
                "nextTaskId": null,
                "collaboration": {
                    "status": false,
                    "currentUsers": []
                },
                "actions": [
                    "ACTION_GETTASK",
                    "ACTION_GETUISETTINGS",
                    "ACTION_CREATEMESSAGE",
                    "ACTION_VIEW_TASK",
                    "ACTION_VIEW_TASK_DETAILS",
                    "ACTION_CANCELCLAIM",
                    "ACTION_COMPLETE",
                    "ACTION_SETOUTPUTMESSAGE",
                    "ACTION_INVITE",
                    "ACTION_UPDATEDUEDATE",
                    "ACTION_UPDATEPRIORITY",
                    "ACTION_REASSIGNTOUSER",
                    "ACTION_REASSIGNTOGROUP"
                ],
                "tkiid": "1327",
                "name": "Zpracovat žádost",
                "status": "Received",
                "owner": "A3KOMA",
                "assignedTo": "A3KOMA",
                "assignedToDisplayName": "PERFORMANCE ALENA",
                "assignedToType": "user",
                "dueTime": "2015-09-08T14:00:12Z"
            }
        }


# Data Structures


## Federation Result (object)
+ indexRefreshInterval: `1000` (number, required)
+ id: `bpm85eiplf1` (string, required)
+ statusCode: `200` (number, required)
+ taskCompletionUrlPrefix: `https://vnvrh687.sos.kb.cz:10402/teamworks`(string, required)
+ restUrlPrefix: `https://vnvrh687.sos.kb.cz:10402/rest/bpm/wle`(string, required)
+ systemType (enum, required)
    + `SYSTEM_TYPE_WLE`
    + `SYSTEM_TYPE_WPS`
+ indexName: `bpm85eiplf1` (string, required)
+ systemID: `d025037a-372b-42c2-ab87-72e3cc9c4bd5` (string, required)
+ version: `8.5.6.0` (string, required)

## Task Query Item (object)
+ authorizationType: `INSTANCE_BASED` (string, required)
+ kind (enum, required)
    + `FEDERATED` (string)
+ entityTypeName (enum, required)
    + `TASK` (string)
+ systemIDs (array, required) - List of system IDs
    + `d025037a-372b-42c2-ab87-72e3cc9c4bd5` (string)
    + `PK:9023014d.add80b66.5f8ef9f5.5c730000` (string)
+ locales (array, required) - Supported locales
    + `default` (string)
    + en (string)
    + cs (string)
+ name (enum, required)
    + KB.TASKLIST (string, required)
+ description: `This is the default KB tasks list. Define custom tasks lists to show selected business data.` (string, required)
+ displayName: `All` (string, required)
+ keyAttribute: `TASK.TKIID` (string, required)

## Attribute Info (object)
+ content: `task.invokedinstanceid.key` (string, required)
+ sourceAttribute: `task.invokedinstanceid.key` (string, required)
+ name: `INVOKED_INSTANCE_ID` (string, required)
+ sourceQueryTableIdentifier: `n/a` (string, required)
+ type: `string` (string, required)
+ isArray: `false` (boolean, required)

## Task Detail (object)

## Task List Item (object)
+ dueTime: `2014-05-05T01:06:40Z` (string, required) - The time when the task is due
+ activationTime: `2015-06-26T09:54:59Z` (string, required) - The creation time of the task
+ completionTime: `2015-06-27T09:54:59Z` (string, required) - The completion time of the task
+ isAtRisk: true (boolean, required) - States whether the task is at risk
+ atRiskTime: `2015-06-26T09:54:59Z` (string, required) - TODO
+ state (enum, required) - The state of the task
    + `STATE_READY` (string) - The task is ready to be worked on
    + `STATE_CLAIMED` (string) - The task is claimed by an user
    + `STATE_FINISHED` (string) - The task is finished
+ name: HT120 (string, required) - Technical name of the task
+ displayName: `Zpracovat žádost` (string, required) - Name of the task to be displayed in UI
+ originator: deadmin (string, required) - TODO
+ priority: 30 (number, required) - Numeric value of the task priority
+ priorityName: Normal (enum, required) - Human readable name of the priority class
+ tkiid: 671 (string, required) - Id of the task
+ TASK.TKIID: 671 (string, required) - Id of the task
+ status (enum, required) - Status of the task
    + `New_or_Received`
    + `Followed`
    + `Replied`
    + `Actioned`
    + `Help_Request`
    + `New` 
    + `Forwarded`
    + `Closed`
    + `Special`
    + `Comment`
    + `Answered_Help_Request`
    + `Tagged`
    + `Ignored_Help_Request`
    + `Received`
    + `Deleted`
    + `Collaboration`
    + `Sent`
    + `Alert`
+ owner: A3KOMA (string, required) - ID of the user who claimed the task, null otherwise 
+ assignedToRoleDisplayName: New Team 3 (string, required) - The display name of the group the task is assigne to, null if the task is claimed
+ description (string, optional)
+ piid: 561 (string, required) - ID of the process instance
+ processInstanceName: Assign Based on Filter Service (string, required) - Name of the process instance to be displayed
+ systemID: `d025037a-372b-42c2-ab87-72e3cc9c4bd5` (string, required) - ID of the system the task belongs to.
+ bd.clientID.long (number, required) - KB ID of the person/company.
+ bd.clientFirstName.string (string, required) - First name of the person. If null, just dont display.
+ bd.clientSearchName.string (string, required) - Last name of person or company name. It may happen that first name is available for company.
+ bd.clientICBirthNumber.long (number, required) - Birth Number of the person or Company ID.
+ bd.clientIsCorporate.long (number, required) - Is the company from Corporate segment?
+ bd.requestId.long (number, required) - The request ID of the client.
+ bd.accountNumber.long (number, required) - The account number of the client.
+ bd.caseID.long (number, required) - The case ID of the business request.
+ bd.caseType.string (string, required) - Type of the case.
+ bd.businessRequestExpiration.date (string, required) - Expiration time of the business request.
+ bd.businessRequestCreatedOn.date (string, required) - The creation time of the business request.
+ bd.businessRequestIsDocNeeded.long (number, required) - States whether documentation is needed for the business request.
+ bd.businessRequestIsDocAttached.long (number, required) - States whether documentation is attached with the business request.
+ bd.businessRequestTitle.string (string, optional) - TODO: use taskDisplayName instead.Business Request title. Only for WMT Tasks. Used in similar way as Process Instance Name.
+ bd.businessRequestId.long (number, required) - Business Request ID.
+ bd.businessSubRequestId.long (number, required) - Business SubRequest ID.

## Federated System (object)
+ systemID: `d025037a-372b-42c2-ab87-72e3cc9c4bd5` (string, optional) - ID of the system that is described by this object.
+ systemType (enum) - Type of the system that is described by this object.
    + SYSTEM_TYPE_WLE (string)
    + SYSTEM_TYPE_WPS (string)
+ version: 8.5.6.0 (string) - Version of the system that is described by this object.
+ buildLevel: `BPM8560-20150304-164853` (string) - Build level of the system that is described by this object.
+ groupWorkItemsEnabled: false (boolean) - States whether group work items can be used.
+ substitutionEnabled: false (boolean) - States whether substitution is enabled.
+ substitutionManagementRestrictedToAdministrators: false  (boolean) - States whether substitution management is restricted to administrators.
+ taskHistoryEnabled: false (boolean) - States whether the collection of task history events is enabled.
+ workBasketsEnabled: false (boolean) - States whether work baskets are enabled.
+ businessCategoriesEnabled: false (boolean) - States whether business categories are enabled.
+ taskSearchEnabled: true (boolean) - States whether task searches are enabled.
+ notificationWebMessagingEnabled: false (boolean) - States whether notifications are enabled.
+ taskListWebMessagingEnabled: false (boolean) - States whether task list auto refresh is enabled.
+ apiVersion: `1.0` (string) - A string indicating the version of the BPM REST API.
+ supports (array[string]) - List of features the API supports.
+ resources (enum) - List of supported resource types.
    + tasks
    + taskTemplates
    + processes
    + escalations
    + workBaskets
    + businessCategories
    + processes
    + processTemplates
    + activities
+ hostName: `brm-ibm-poc.kb.cz` (string) - Hostname of the system that is described by this object.
+ serverLocale: `en_US` (string, optional)







